/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.ConnectorSchema = factory(root.RusticiSoftwareCloudV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ConnectorSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/ConnectorSchema
   */

  /**
   * Constructs a new <code>ConnectorSchema</code>.
   * A content connector.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ConnectorSchema
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>ConnectorSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ConnectorSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ConnectorSchema} The populated <code>ConnectorSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('connectorId'))
        obj.connectorId = ApiClient.convertToType(data['connectorId'], 'String');
      if (data.hasOwnProperty('contentConnectorType'))
        obj.contentConnectorType = ApiClient.convertToType(data['contentConnectorType'], 'String');
      if (data.hasOwnProperty('configuration'))
        obj.configuration = ApiClient.convertToType(data['configuration'], Object);
      if (data.hasOwnProperty('additionalInstanceInformation'))
        obj.additionalInstanceInformation = ApiClient.convertToType(data['additionalInstanceInformation'], Object);
      if (data.hasOwnProperty('enabled'))
        obj.enabled = ApiClient.convertToType(data['enabled'], 'Boolean');
    }
    return obj;
  }

  /**
   * @member {String} connectorId
   */
  exports.prototype.connectorId = undefined;

  /**
   * type of this content connector
   * @member {String} contentConnectorType
   */
  exports.prototype.contentConnectorType = undefined;

  /**
   * configuration for this content connector, format is implementation specific
   * @member {Object} configuration
   */
  exports.prototype.configuration = undefined;

  /**
   * additional information about this content connector, format is implementation specific and will only be present if the connector is enabled
   * @member {Object} additionalInstanceInformation
   */
  exports.prototype.additionalInstanceInformation = undefined;

  /**
   * is this connector enabled
   * @member {Boolean} enabled
   */
  exports.prototype.enabled = undefined;


  return exports;

}));
