/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient', 'rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchIdSchema'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./CreateDispatchIdSchema'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.CreateDispatchListSchema = factory(root.RusticiSoftwareCloudV2.ApiClient, root.RusticiSoftwareCloudV2.CreateDispatchIdSchema);
  }
}(this, function(ApiClient, CreateDispatchIdSchema) {
  'use strict';




  /**
   * The CreateDispatchListSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchListSchema
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>CreateDispatchListSchema</code>.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchListSchema
   * @class
   */
  var exports = function() {
    var _this = this;


  };

  /**
   * Constructs a <code>CreateDispatchListSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchListSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchListSchema} The populated <code>CreateDispatchListSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('dispatches')) {
        obj['dispatches'] = ApiClient.convertToType(data['dispatches'], [CreateDispatchIdSchema]);
      }
    }
    return obj;
  }

  /**
   * @member {Array.<module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/CreateDispatchIdSchema>} dispatches
   */
  exports.prototype['dispatches'] = undefined;



  return exports;
}));


