/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient', 'rustici-software-cloud-v2/rustici-software-cloud-v2-model/MediaFileMetadataSchema'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./MediaFileMetadataSchema'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.ImportMediaFileReferenceRequestSchema = factory(root.RusticiSoftwareCloudV2.ApiClient, root.RusticiSoftwareCloudV2.MediaFileMetadataSchema);
  }
}(this, function(ApiClient, MediaFileMetadataSchema) {
  'use strict';

  /**
   * The ImportMediaFileReferenceRequestSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/ImportMediaFileReferenceRequestSchema
   */

  /**
   * Constructs a new <code>ImportMediaFileReferenceRequestSchema</code>.
   * Used to create a course that references a media file. Upon import, the actual file is not downloaded and stored on SCORM Cloud's servers. Instead, the media file wrapper will load the content from the provided URL. 
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ImportMediaFileReferenceRequestSchema
   * @class
   * @param url {String} URL path to the media file to use when launching this course
   * @param contentType {String} MIME type of the media file
   */
  var exports = function(url, contentType) {
    this.url = url;
    this.contentType = contentType;
  };

  /**
   * Constructs a <code>ImportMediaFileReferenceRequestSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ImportMediaFileReferenceRequestSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ImportMediaFileReferenceRequestSchema} The populated <code>ImportMediaFileReferenceRequestSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('contentType'))
        obj.contentType = ApiClient.convertToType(data['contentType'], 'String');
      if (data.hasOwnProperty('mediaFileMetadata'))
        obj.mediaFileMetadata = MediaFileMetadataSchema.constructFromObject(data['mediaFileMetadata']);
    }
    return obj;
  }

  /**
   * URL path to the media file to use when launching this course
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * MIME type of the media file
   * @member {String} contentType
   */
  exports.prototype.contentType = undefined;

  /**
   * @member {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/MediaFileMetadataSchema} mediaFileMetadata
   */
  exports.prototype.mediaFileMetadata = undefined;


  return exports;

}));
