/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.InvitationEmailSchema = factory(root.RusticiSoftwareCloudV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The InvitationEmailSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/InvitationEmailSchema
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InvitationEmailSchema</code>.
   * Object representing an e-mail to be sent to a given list of e-mail addresses inviting them to participate in a course.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/InvitationEmailSchema
   * @class
   * @param addresses {Array.<String>} A comma separated list of email addresses to which this invitation will be sent.  NOTE: registrations with automatically be create for each of these e-mail addresses.
   */
  var exports = function(addresses) {
    var _this = this;



    _this['addresses'] = addresses;
  };

  /**
   * Constructs a <code>InvitationEmailSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/InvitationEmailSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/InvitationEmailSchema} The populated <code>InvitationEmailSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('subject')) {
        obj['subject'] = ApiClient.convertToType(data['subject'], 'String');
      }
      if (data.hasOwnProperty('body')) {
        obj['body'] = ApiClient.convertToType(data['body'], 'String');
      }
      if (data.hasOwnProperty('addresses')) {
        obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
      }
    }
    return obj;
  }

  /**
   * The subject line for the email.
   * @member {String} subject
   */
  exports.prototype['subject'] = undefined;
  /**
   * The body of the email.
   * @member {String} body
   */
  exports.prototype['body'] = undefined;
  /**
   * A comma separated list of email addresses to which this invitation will be sent.  NOTE: registrations with automatically be create for each of these e-mail addresses.
   * @member {Array.<String>} addresses
   */
  exports.prototype['addresses'] = undefined;



  return exports;
}));


