/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.ReportageAccountInfoUsageSchema = factory(root.RusticiSoftwareCloudV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The ReportageAccountInfoUsageSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/ReportageAccountInfoUsageSchema
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>ReportageAccountInfoUsageSchema</code>.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ReportageAccountInfoUsageSchema
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>ReportageAccountInfoUsageSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ReportageAccountInfoUsageSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ReportageAccountInfoUsageSchema} The populated <code>ReportageAccountInfoUsageSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('monthStart')) {
        obj['monthStart'] = ApiClient.convertToType(data['monthStart'], 'Date');
      }
      if (data.hasOwnProperty('regCount')) {
        obj['regCount'] = ApiClient.convertToType(data['regCount'], 'Number');
      }
      if (data.hasOwnProperty('totalRegistrations')) {
        obj['totalRegistrations'] = ApiClient.convertToType(data['totalRegistrations'], 'Number');
      }
      if (data.hasOwnProperty('totalCourses')) {
        obj['totalCourses'] = ApiClient.convertToType(data['totalCourses'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Date} monthStart
   */
  exports.prototype['monthStart'] = undefined;
  /**
   * @member {Number} regCount
   */
  exports.prototype['regCount'] = undefined;
  /**
   * @member {Number} totalRegistrations
   */
  exports.prototype['totalRegistrations'] = undefined;
  /**
   * @member {Number} totalCourses
   */
  exports.prototype['totalCourses'] = undefined;



  return exports;
}));


