/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient', 'rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchemaRegistrationReport'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./UserInvitationSchemaRegistrationReport'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.UserInvitationSchema = factory(root.RusticiSoftwareCloudV2.ApiClient, root.RusticiSoftwareCloudV2.UserInvitationSchemaRegistrationReport);
  }
}(this, function(ApiClient, UserInvitationSchemaRegistrationReport) {
  'use strict';

  /**
   * The UserInvitationSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchema
   * @version 2.0.0
   */

  /**
   * Constructs a new <code>UserInvitationSchema</code>.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchema
   * @class
   */
  var exports = function() {
  };

  /**
   * Constructs a <code>UserInvitationSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchema} The populated <code>UserInvitationSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
      if (data.hasOwnProperty('url'))
        obj.url = ApiClient.convertToType(data['url'], 'String');
      if (data.hasOwnProperty('isStarted'))
        obj.isStarted = ApiClient.convertToType(data['isStarted'], 'Boolean');
      if (data.hasOwnProperty('updated'))
        obj.updated = ApiClient.convertToType(data['updated'], 'Date');
      if (data.hasOwnProperty('registrationId'))
        obj.registrationId = ApiClient.convertToType(data['registrationId'], 'String');
      if (data.hasOwnProperty('registrationReport'))
        obj.registrationReport = UserInvitationSchemaRegistrationReport.constructFromObject(data['registrationReport']);
    }
    return obj;
  }

  /**
   * The email of the user who took an invitation.
   * @member {String} email
   */
  exports.prototype.email = undefined;

  /**
   * The URL which the user would follow to take the invitation.
   * @member {String} url
   */
  exports.prototype.url = undefined;

  /**
   * A boolean flag stating if the user has started the invitation.
   * @member {Boolean} isStarted
   */
  exports.prototype.isStarted = undefined;

  /**
   * @member {Date} updated
   */
  exports.prototype.updated = undefined;

  /**
   * The id of the registration which was created from the user being invited.
   * @member {String} registrationId
   */
  exports.prototype.registrationId = undefined;

  /**
   * @member {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/UserInvitationSchemaRegistrationReport} registrationReport
   */
  exports.prototype.registrationReport = undefined;


  return exports;

}));
