/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.27
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient', 'rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivityDefinition'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./XapiActivityDefinition'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.XapiActivity = factory(root.RusticiSoftwareCloudV2.ApiClient, root.RusticiSoftwareCloudV2.XapiActivityDefinition);
  }
}(this, function(ApiClient, XapiActivityDefinition) {
  'use strict';

  /**
   * The XapiActivity model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivity
   */

  /**
   * Constructs a new <code>XapiActivity</code>.
   * https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#4141-when-the-objecttype-is-activity
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivity
   * @class
   * @param id {String} 
   */
  var exports = function(id) {
    this.id = id;
  };

  /**
   * Constructs a <code>XapiActivity</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivity} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivity} The populated <code>XapiActivity</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('objectType'))
        obj.objectType = ApiClient.convertToType(data['objectType'], 'String');
      if (data.hasOwnProperty('id'))
        obj.id = ApiClient.convertToType(data['id'], 'String');
      if (data.hasOwnProperty('definition'))
        obj.definition = XapiActivityDefinition.constructFromObject(data['definition']);
    }
    return obj;
  }

  /**
   * @member {String} objectType
   * @default 'Activity'
   */
  exports.prototype.objectType = 'Activity';

  /**
   * @member {String} id
   */
  exports.prototype.id = undefined;

  /**
   * @member {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiActivityDefinition} definition
   */
  exports.prototype.definition = undefined;


  return exports;

}));
