/**
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.XapiScore = factory(root.RusticiSoftwareCloudV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The XapiScore model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiScore
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>XapiScore</code>.
   * https://github.com/adlnet/xAPI-Spec/blob/1.0.2/xAPI.md#4151-score
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiScore
   * @class
   */
  var exports = function() {
    var _this = this;





  };

  /**
   * Constructs a <code>XapiScore</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiScore} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/XapiScore} The populated <code>XapiScore</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('scaled')) {
        obj['scaled'] = ApiClient.convertToType(data['scaled'], 'Number');
      }
      if (data.hasOwnProperty('raw')) {
        obj['raw'] = ApiClient.convertToType(data['raw'], 'Number');
      }
      if (data.hasOwnProperty('min')) {
        obj['min'] = ApiClient.convertToType(data['min'], 'Number');
      }
      if (data.hasOwnProperty('max')) {
        obj['max'] = ApiClient.convertToType(data['max'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} scaled
   */
  exports.prototype['scaled'] = undefined;
  /**
   * @member {Number} raw
   */
  exports.prototype['raw'] = undefined;
  /**
   * @member {Number} min
   */
  exports.prototype['min'] = undefined;
  /**
   * @member {Number} max
   */
  exports.prototype['max'] = undefined;



  return exports;
}));


