/*
 * SCORM Cloud Rest API
 * REST API used for SCORM Cloud integrations.
 *
 * OpenAPI spec version: 2.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.12
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['rustici-software-cloud-v2/ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.RusticiSoftwareCloudV2) {
      root.RusticiSoftwareCloudV2 = {};
    }
    root.RusticiSoftwareCloudV2.ZoomiCourseOptionsSchema = factory(root.RusticiSoftwareCloudV2.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';

  /**
   * The ZoomiCourseOptionsSchema model module.
   * @module rustici-software-cloud-v2/rustici-software-cloud-v2-model/ZoomiCourseOptionsSchema
   * @version 2.0.1
   */

  /**
   * Constructs a new <code>ZoomiCourseOptionsSchema</code>.
   * @alias module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ZoomiCourseOptionsSchema
   * @class
   * @param nti {String} 
   * @param cta {String} 
   */
  var exports = function(nti, cta) {
    this.nti = nti;
    this.cta = cta;
  };

  /**
   * Constructs a <code>ZoomiCourseOptionsSchema</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ZoomiCourseOptionsSchema} obj Optional instance to populate.
   * @return {module:rustici-software-cloud-v2/rustici-software-cloud-v2-model/ZoomiCourseOptionsSchema} The populated <code>ZoomiCourseOptionsSchema</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();
      if (data.hasOwnProperty('nti'))
        obj.nti = ApiClient.convertToType(data['nti'], 'String');
      if (data.hasOwnProperty('cta'))
        obj.cta = ApiClient.convertToType(data['cta'], 'String');
    }
    return obj;
  }

  /**
   * @member {String} nti
   */
  exports.prototype.nti = undefined;

  /**
   * @member {String} cta
   */
  exports.prototype.cta = undefined;


  return exports;

}));
